### ISSUE TITLE
Command syntax confusion

### ISSUE THREAD

**Issue by LemADEC** [SimonFlash/CmdCalendar#1]
As of CmdCalendar-mc1.10.2-1.0.0.jar

1- The command syntax is documented through tool-tips in game, but readme doesn't show tool-tips so we're left guessing what "type" values are possible, etc.

2- Readme says
```
/CmdCal CreateTask <Name> <Type>: Creates a task named Name of type Type
```
while ingame says:
```
/CmdCal CreateTask <Type> <Name>
```
Only the first syntax actually works.

3- Readme and ingame debug talks about Concealed tasks but doesn't explain what they are.
Using the command doesn't say anything in chat.

**Comment by SimonFlash** [comment]
1: Hovering over any command term in the help menu will display various information including the possible values about that term. (current)
2: Error after rewriting EditTask. The correct format is <Name> <Type>; and the help menu has been adjusted accordingly. (new v1.1.0)
3: Concealed tasks are unimplemented, but will allow tasks to be hid from the task list. (unknown)
