### ISSUE TITLE
Configuration not loading nor saving properly

### ISSUE THREAD

**Issue by LemADEC** [SimonFlash/CmdCalendar#5]
As of CmdCalendar-mc1.10.2-1.0.0.jar,
Configuration loading through boot or /debug command, will always report "no tasks".
Configuration saving is forcing status=Halted even when a newly created task is Active.

Steps to reproduce:
1- remove all tasks from configuration, just keep:
2- type below commands
```
cmdcal create sun interval
cmdcal edit sun command weather Eden clear
cmdcal edit sun interval 300
cmdcal edit sun description no rain, no pain
cmdcal list
```
=> task is reported as active
```
cmdcal debug saveconfig confirm
cmdcal debug loadconfig confirm
cmdcal list
```
=> no task is reported

3- open configuration file
```
    sun {
        command="weather Eden clear"
        description="no rain, no pain"
        interval=300
        status=Halted
        type=Interval
    }
```
=> task is saved as halted

**Comment by SimonFlash** [comment]
Caused by misplaced debug code in RunTask#syncTasks; fixed for the next version (new v1.1.0)
