### ISSUE TITLE
Configuration loading forcing task_blacklist

### ISSUE THREAD

**Issue by LemADEC** [SimonFlash/CmdCalendar#6]
As of CmdCalendar-mc1.10.2-1.0.0.jar,
whenever the loadconfig command is used, a new set of default values is added to task_blacklist.
This preventing us to customize this parameter.
This causing lots of duplicated entries in the configuration too.

**Comment by SimonFlash** [comment]
Caused by an inverted if statement; fixed for the next version. (new v1.1.0)
