### ISSUE TITLE
Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by Charismara** [SimonFlash/CmdCalendar#8]
Hi,
i wanted to use CmdScheduler but the Server always crash with this Plugin.
[Here ](https://pastebin.com/iZiSZ2BL)is my Crashlog.
 I hope u can fix this 😄.

**Comment by SimonFlash** [comment]
You need to install CmdControl as a dependency. Please read the release notes of plugins before downloading it. CmdScheduler 1.2.0 is compatible with CmdControl 1.2.0.

**Comment by Charismara** [comment]
The Server starts now and Cmdcontrol works but cmdscheduler doesn't work.

[This](https://pastebin.com/d3rUxwa7) is what i fround in my log.

**Comment by SimonFlash** [comment]
You're running CmdControl v1.2.0 with CmdScheduler v1.0.0, which are incompatible. My earlier comment is mistaken as CmdScheduler v1.2.0 is not publicly released yet, so you should be using v1.1.0 of both for the meantime. You can find downloads on [Ore](https://ore.spongepowered.org/Simon_Flash/CmdScheduler/versions/1.1.0).

GitHub issues should be reserved for problems with the plugin, not for support. If you need assistance with setup, you can join my [support discord](https://discord.gg/4wayq37).
